version: '3'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MYSQLUSER=mysql
      - MYSQLHOST=mysql
      - MYSQLDATABASE=CallCenterDB
      - MYSQLPASSWORD=password
      - MYSQLPORT=3306
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
